theme: minima
title: Brittany Judson: Digital Portfolio
author: Brittany Judson
email: brit.e.villarmino@gmail.com.com
description: > # this means to ignore newlines until "baseurl:"
  This is a website displaying content authored by Brittany Judson. Brittany is based in Atlanta, GA, is an Agnes Scott grad, and is a consultant at a nonprofit called the Partnership for Southern Equity. This is her first time making a website on GitHub. On this site, you'll find the following sections: About Brittany, Resume, Work Experience, Economic Research, GitHub Repository, and other fun stuff. 

# social links
twitter_username: britjud # DO NOT include the @ character, or else the build will fail!
github_username:  britjudson # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
